# Generated by Django 5.0.2 on 2024-02-11 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "name",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("name_ru", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="IMDb",
            fields=[
                (
                    "imdb_mvid",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("type", models.CharField(max_length=20)),
                ("title_en", models.CharField(max_length=200)),
                ("title_ru", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200)),
                ("is_adult", models.BooleanField()),
                ("runtime", models.SmallIntegerField()),
                ("rate", models.FloatField()),
                ("votes", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="KP",
            fields=[
                (
                    "kp_mvid",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("tagline_ru", models.TextField()),
                ("overview_ru", models.TextField()),
                ("rate", models.FloatField()),
                ("votes", models.IntegerField()),
                ("rate_fc", models.FloatField()),
                ("votes_fc", models.IntegerField()),
                ("rate_rfc", models.FloatField()),
                ("votes_rfc", models.IntegerField()),
                (
                    "imdb_mvid",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="movies.imdb"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductionCompany",
            fields=[
                ("company", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("image_url", models.URLField(blank=True, null=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="movies.country"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TMDb",
            fields=[
                ("tmdb_mvid", models.IntegerField(primary_key=True, serialize=False)),
                ("collection", models.IntegerField()),
                ("release_date", models.DateField()),
                ("budget", models.IntegerField()),
                ("revenue", models.IntegerField()),
                ("image_url", models.URLField()),
                ("tagline_en", models.TextField()),
                ("overview_en", models.TextField()),
                ("rate", models.FloatField()),
                ("votes", models.IntegerField()),
                ("populatiry", models.FloatField()),
                (
                    "imdb_mvid",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="movies.imdb"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MovieProduction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imdb_mvid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="movies.imdb"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="movies.productioncompany",
                    ),
                ),
                (
                    "tmdb_mvid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="movies.tmdb"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MovieCountry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imdb_mvid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="movies.imdb"
                    ),
                ),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="movies.country"
                    ),
                ),
                (
                    "tmdb_mvid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="movies.tmdb"
                    ),
                ),
            ],
        ),
    ]
