# Generated by Django 5.0.2 on 2024-02-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="imdb",
            name="kp_added",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="imdb",
            name="tmdb_added",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="imdb",
            name="wrate",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="imdb",
            name="rate",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="imdb",
            name="runtime",
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="imdb",
            name="title_ru",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="imdb",
            name="votes",
            field=models.IntegerField(null=True),
        ),
    ]
