# Generated by Django 5.0.2 on 2024-02-14 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_imdb_kp_added_imdb_tmdb_added_imdb_wrate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imdb_name", models.CharField(max_length=200)),
                ("tmdb_name", models.CharField(max_length=200)),
                ("kp_name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="MovieGenres",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="movies.genre"
                    ),
                ),
                (
                    "imdb_mvid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="movies.imdb"
                    ),
                ),
            ],
        ),
    ]
