# Generated by Django 5.0.2 on 2024-02-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_genre_moviegenres"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imdb",
            name="slug",
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
