# Generated by Django 5.0.2 on 2024-02-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0005_alter_genre_kp_name_alter_genre_tmdb_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="genre",
            name="slug",
            field=models.SlugField(default="slug", max_length=200),
            preserve_default=False,
        ),
    ]
