# Generated by Django 5.0.2 on 2024-02-15 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0006_genre_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="genre",
            options={"verbose_name": "Genre", "verbose_name_plural": "Genre"},
        ),
    ]
