# Generated by Django 5.0.2 on 2024-02-15 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0007_alter_genre_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="genre",
            options={"verbose_name": "Genre", "verbose_name_plural": "Genres"},
        ),
        migrations.AlterModelOptions(
            name="imdb",
            options={"verbose_name": "Фильмы IMDb"},
        ),
        migrations.AlterModelOptions(
            name="moviegenres",
            options={
                "verbose_name": "Жанр фильма",
                "verbose_name_plural": "Жанры фильма",
            },
        ),
        migrations.AlterField(
            model_name="genre",
            name="imdb_name",
            field=models.CharField(max_length=200, verbose_name="Название IMDb"),
        ),
        migrations.AlterField(
            model_name="genre",
            name="kp_name",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Название KP"
            ),
        ),
        migrations.AlterField(
            model_name="genre",
            name="slug",
            field=models.SlugField(max_length=200, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="genre",
            name="tmdb_name",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Название TMDb"
            ),
        ),
        migrations.AlterField(
            model_name="imdb",
            name="imdb_mvid",
            field=models.CharField(
                max_length=20,
                primary_key=True,
                serialize=False,
                verbose_name="Код IMDb",
            ),
        ),
        migrations.AlterField(
            model_name="imdb",
            name="is_adult",
            field=models.BooleanField(verbose_name="Для взрослых"),
        ),
        migrations.AlterField(
            model_name="imdb",
            name="rate",
            field=models.FloatField(null=True, verbose_name="Рейтинг IMDb"),
        ),
        migrations.AlterField(
            model_name="imdb",
            name="runtime",
            field=models.SmallIntegerField(null=True, verbose_name="Время"),
        ),
        migrations.AlterField(
            model_name="imdb",
            name="slug",
            field=models.SlugField(max_length=200, unique=True, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="imdb",
            name="title_en",
            field=models.CharField(max_length=200, verbose_name="Название англ."),
        ),
        migrations.AlterField(
            model_name="imdb",
            name="title_ru",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Название рус."
            ),
        ),
        migrations.AlterField(
            model_name="imdb",
            name="type",
            field=models.CharField(max_length=20, verbose_name="Тип фильма"),
        ),
        migrations.AlterField(
            model_name="imdb",
            name="votes",
            field=models.IntegerField(
                null=True, verbose_name="Количество голосов IMDb"
            ),
        ),
        migrations.AlterField(
            model_name="imdb",
            name="wrate",
            field=models.FloatField(null=True, verbose_name="Относительный рейтинг"),
        ),
        migrations.AlterField(
            model_name="moviegenres",
            name="genre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="movies.genre",
                verbose_name="Жанр",
            ),
        ),
        migrations.AlterField(
            model_name="moviegenres",
            name="imdb_mvid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="movies.imdb",
                verbose_name="Код IMDb",
            ),
        ),
    ]
