# Generated by Django 5.0.2 on 2024-02-15 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0008_alter_genre_options_alter_imdb_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="genre",
            options={"verbose_name": "Жанр", "verbose_name_plural": "Жанры"},
        ),
        migrations.AlterModelOptions(
            name="imdb",
            options={
                "verbose_name": "Фильм IMDb",
                "verbose_name_plural": "Фильмы IMDb",
            },
        ),
    ]
