# Generated by Django 5.0.2 on 2024-02-15 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0009_alter_genre_options_alter_imdb_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="tmdb",
            name="overview_ru",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tmdb",
            name="tagline_ru",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="moviegenres",
            name="imdb_mvid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="movies.imdb",
                verbose_name="Название IMDb",
            ),
        ),
    ]
