# Generated by Django 5.0.2 on 2024-02-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0010_tmdb_overview_ru_tmdb_tagline_ru_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tmdb",
            name="budget",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tmdb",
            name="collection",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tmdb",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tmdb",
            name="overview_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tmdb",
            name="overview_ru",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tmdb",
            name="populatiry",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tmdb",
            name="rate",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tmdb",
            name="release_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tmdb",
            name="revenue",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tmdb",
            name="tagline_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tmdb",
            name="tagline_ru",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tmdb",
            name="votes",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
