# Generated by Django 5.0.2 on 2024-02-15 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0011_alter_tmdb_budget_alter_tmdb_collection_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tmdb",
            old_name="populatiry",
            new_name="popularity",
        ),
    ]
