# Generated by Django 5.0.2 on 2024-02-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0013_collection_alter_tmdb_collection"),
    ]

    operations = [
        migrations.RenameField(
            model_name="collection",
            old_name="name",
            new_name="name_en",
        ),
        migrations.AddField(
            model_name="collection",
            name="name_ru",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
