# Generated by Django 5.0.2 on 2024-02-15 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0014_rename_name_collection_name_en_collection_name_ru"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collection",
            options={"verbose_name": "Коллекция", "verbose_name_plural": "Коллекции"},
        ),
        migrations.AlterModelOptions(
            name="country",
            options={"verbose_name": "Страна", "verbose_name_plural": "Страны"},
        ),
        migrations.AlterModelOptions(
            name="moviecountry",
            options={
                "verbose_name": "Страна фильма",
                "verbose_name_plural": "Страны фильма",
            },
        ),
        migrations.AlterModelOptions(
            name="movieproduction",
            options={
                "verbose_name": "Продюсерская компания фильма",
                "verbose_name_plural": "Продюсерские компании фильма",
            },
        ),
        migrations.AlterModelOptions(
            name="productioncompany",
            options={
                "verbose_name": "Продюсерская компания",
                "verbose_name_plural": "Продюсерские компании",
            },
        ),
        migrations.AlterModelOptions(
            name="tmdb",
            options={
                "verbose_name": "Фильм TMDb",
                "verbose_name_plural": "Фильмы TMDb",
            },
        ),
    ]
