# Generated by Django 5.0.2 on 2024-02-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0016_alter_productioncompany_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productioncompany",
            name="country",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
