# Generated by Django 5.0.2 on 2024-02-15 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0017_alter_productioncompany_country"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="genre",
            name="kp_name",
        ),
        migrations.AddField(
            model_name="genre",
            name="name_ru",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Название на русском",
            ),
        ),
    ]
