# Generated by Django 5.0.2 on 2024-02-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "movies",
            "0020_rename_kp_added_imdb_imdb_extra_added_imdb_image_url_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="tmdb",
            name="budget",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tmdb",
            name="revenue",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
