# Generated by Django 5.0.2 on 2024-02-18 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0021_alter_tmdb_budget_alter_tmdb_revenue"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="moviecountry",
            name="name",
        ),
        migrations.AddField(
            model_name="moviecountry",
            name="country",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movies",
                to="movies.country",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="moviecountry",
            name="imdb_mvid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="countries",
                to="movies.imdb",
            ),
        ),
        migrations.AlterField(
            model_name="moviecountry",
            name="tmdb_mvid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="countries",
                to="movies.tmdb",
            ),
        ),
        migrations.AlterField(
            model_name="moviegenre",
            name="genre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movies",
                to="movies.genre",
                verbose_name="Жанр",
            ),
        ),
        migrations.AlterField(
            model_name="moviegenre",
            name="imdb_mvid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="genres",
                to="movies.imdb",
                verbose_name="Название IMDb",
            ),
        ),
        migrations.AlterField(
            model_name="tmdb",
            name="imdb_mvid",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tmdb",
                to="movies.imdb",
            ),
        ),
    ]
