"""empty message

Revision ID: 7b30cd7ec90e
Revises: e6e836c5a69f
Create Date: 2024-05-04 17:12:53.817354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b30cd7ec90e'
down_revision: Union[str, None] = 'e6e836c5a69f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('collection', 'name_ru',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('collection_name_ru_key', 'collection', type_='unique')
    op.create_unique_constraint(None, 'movie_country', ['country', 'imdb_movie'])
    op.create_unique_constraint(None, 'movie_country', ['country', 'tmdb_movie'])
    op.create_unique_constraint(None, 'movie_genre', ['imdb_movie', 'genre'])
    op.create_unique_constraint(None, 'movie_production', ['production_company', 'imdb_movie'])
    op.create_unique_constraint(None, 'movie_production', ['production_company', 'tmdb_movie'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movie_production', type_='unique')
    op.drop_constraint(None, 'movie_production', type_='unique')
    op.drop_constraint(None, 'movie_genre', type_='unique')
    op.drop_constraint(None, 'movie_country', type_='unique')
    op.drop_constraint(None, 'movie_country', type_='unique')
    op.create_unique_constraint('collection_name_ru_key', 'collection', ['name_ru'])
    op.alter_column('collection', 'name_ru',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
