"""empty message

Revision ID: 0c75764b3c3d
Revises: 9ee4f2b574fe
Create Date: 2024-07-16 19:55:40.253134

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0c75764b3c3d"
down_revision: Union[str, None] = "9ee4f2b574fe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "usermodel",
        "hashed_password",
        existing_type=sa.VARCHAR(),
        type_=sa.LargeBinary(),
        existing_nullable=False,
        postgresql_using="hashed_password::bytea",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "usermodel",
        "hashed_password",
        existing_type=sa.LargeBinary(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
        postgresql_using="hashed_password::varchar",
    )
    # ### end Alembic commands ###
