"""empty message

Revision ID: 24251e2239a6
Revises: 49da6854efdf
Create Date: 2024-07-03 16:13:07.192445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24251e2239a6'
down_revision: Union[str, None] = '49da6854efdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('__test_relation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attr1', sa.String(), nullable=False),
    sa.Column('attr2', sa.String(), nullable=False),
    sa.Column('attr3', sa.String(), nullable=False),
    sa.Column('attr4', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attr1'),
    sa.UniqueConstraint('attr2'),
    sa.UniqueConstraint('attr3')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('__test_relation')
    # ### end Alembic commands ###
