"""empty message

Revision ID: 393ab5bf6cb1
Revises: 24251e2239a6
Create Date: 2024-07-03 16:14:56.487166

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "393ab5bf6cb1"
down_revision: Union[str, None] = "24251e2239a6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        "ALTER TABLE __test_relation ALTER COLUMN attr1 TYPE INTEGER USING (attr1::integer)"
    )
    op.execute(
        "ALTER TABLE __test_relation ALTER COLUMN attr2 TYPE INTEGER USING (attr2::integer)"
    )
    op.execute(
        "ALTER TABLE __test_relation ALTER COLUMN attr3 TYPE INTEGER USING (attr3::integer)"
    )
    op.execute(
        "ALTER TABLE __test_relation ALTER COLUMN attr4 TYPE INTEGER USING (CASE WHEN attr4 IS NOT NULL THEN attr4::integer ELSE NULL END)"
    )

    # # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('__test_relation', 'attr1',
    #            existing_type=sa.VARCHAR(),
    #            type_=sa.Integer(),
    #            existing_nullable=False)
    # op.alter_column('__test_relation', 'attr2',
    #            existing_type=sa.VARCHAR(),
    #            type_=sa.Integer(),
    #            existing_nullable=False)
    # op.alter_column('__test_relation', 'attr3',
    #            existing_type=sa.VARCHAR(),
    #            type_=sa.Integer(),
    #            existing_nullable=False)
    # op.alter_column('__test_relation', 'attr4',
    #            existing_type=sa.VARCHAR(),
    #            type_=sa.Integer(),
    #            existing_nullable=True)
    # # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "__test_relation",
        "attr4",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    op.alter_column(
        "__test_relation",
        "attr3",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.alter_column(
        "__test_relation",
        "attr2",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.alter_column(
        "__test_relation",
        "attr1",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
