"""empty message

Revision ID: 3def51766410
Revises: 393ab5bf6cb1
Create Date: 2024-07-04 20:53:56.885386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3def51766410'
down_revision: Union[str, None] = '393ab5bf6cb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movie_principal', 'job',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movie_principal', 'job',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
