"""empty message

Revision ID: 49da6854efdf
Revises: 303f17b57d76
Create Date: 2024-06-23 15:48:47.891001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49da6854efdf'
down_revision: Union[str, None] = '303f17b57d76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie_principal', sa.Column('ordering', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie_principal', 'ordering')
    # ### end Alembic commands ###
