"""empty message

Revision ID: 5852e2518d71
Revises: 
Create Date: 2024-07-16 12:48:18.913758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5852e2518d71'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('__test_relation',
    sa.Column('attr1', sa.Integer(), nullable=False),
    sa.Column('attr2', sa.Integer(), nullable=False),
    sa.Column('attr3', sa.Integer(), nullable=False),
    sa.Column('attr4', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attr1'),
    sa.UniqueConstraint('attr2'),
    sa.UniqueConstraint('attr3')
    )
    op.create_table('collection',
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('name_en', sa.String(), nullable=False),
    sa.Column('name_ru', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_en'),
    sa.UniqueConstraint('tmdb_id')
    )
    op.create_table('content_type',
    sa.Column('name_en', sa.String(length=40), nullable=False),
    sa.Column('name_ru', sa.String(length=40), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_en'),
    sa.UniqueConstraint('name_ru')
    )
    op.create_table('country',
    sa.Column('iso', sa.String(), nullable=False),
    sa.Column('name_en', sa.String(), nullable=False),
    sa.Column('name_ru', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iso'),
    sa.UniqueConstraint('name_en'),
    sa.UniqueConstraint('name_ru')
    )
    op.create_table('genre',
    sa.Column('name_en', sa.String(), nullable=False),
    sa.Column('name_ru', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('tmdb_name', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_en'),
    sa.UniqueConstraint('name_ru'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('imdb_person',
    sa.Column('imdb_nmid', sa.String(), nullable=False),
    sa.Column('name_en', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('birth_y', sa.Integer(), nullable=True),
    sa.Column('death_y', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('tmdb_added', sa.Boolean(), nullable=False),
    sa.Column('imdb_extra_added', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('imdb_nmid'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('profession',
    sa.Column('imdb_name', sa.String(), nullable=False),
    sa.Column('name_en', sa.String(), nullable=False),
    sa.Column('name_ru', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('imdb_name'),
    sa.UniqueConstraint('name_en'),
    sa.UniqueConstraint('name_ru')
    )
    op.create_table('imdb_movie',
    sa.Column('imdb_mvid', sa.String(length=20), nullable=False),
    sa.Column('name_en', sa.String(), nullable=False),
    sa.Column('name_ru', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('is_adult', sa.Boolean(), nullable=False),
    sa.Column('runtime', sa.SmallInteger(), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('wrate', sa.Float(), nullable=True),
    sa.Column('votes', sa.Integer(), nullable=True),
    sa.Column('start_year', sa.Integer(), nullable=False),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.Column('imdb_extra_added', sa.Boolean(), nullable=False),
    sa.Column('tmdb_added', sa.Boolean(), nullable=False),
    sa.Column('principals_added', sa.Boolean(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('content_type', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['content_type'], ['content_type.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('imdb_mvid'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('person_profession',
    sa.Column('profession_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['imdb_person.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profession_id'], ['profession.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profession_id', 'person_id')
    )
    op.create_table('production_company',
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('name_en', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('country', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country'], ['country.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_en'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('tmdb_id')
    )
    op.create_table('tmdb_person',
    sa.Column('tmdb_nmid', sa.Integer(), nullable=False),
    sa.Column('name_en', sa.String(), nullable=False),
    sa.Column('name_ru', sa.String(), nullable=True),
    sa.Column('gender', sa.Integer(), nullable=False),
    sa.Column('imdb_person', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['imdb_person'], ['imdb_person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('imdb_person'),
    sa.UniqueConstraint('tmdb_nmid')
    )
    op.create_table('movie_genre',
    sa.Column('imdb_movie_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['imdb_movie_id'], ['imdb_movie.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('imdb_movie_id', 'genre_id')
    )
    op.create_table('movie_principal',
    sa.Column('ordering', sa.Integer(), nullable=False),
    sa.Column('job', sa.String(), nullable=True),
    sa.Column('characters', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('imdb_movie_id', sa.Integer(), nullable=False),
    sa.Column('imdb_person_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['profession.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['imdb_movie_id'], ['imdb_movie.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['imdb_person_id'], ['imdb_person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('imdb_movie_id', 'imdb_person_id', 'category_id')
    )
    op.create_table('tmdb_movie',
    sa.Column('tmdb_mvid', sa.Integer(), nullable=False),
    sa.Column('release_date', sa.DateTime(), nullable=True),
    sa.Column('budget', sa.BigInteger(), nullable=True),
    sa.Column('revenue', sa.BigInteger(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('tagline_en', sa.Text(), nullable=True),
    sa.Column('overview_en', sa.Text(), nullable=True),
    sa.Column('tagline_ru', sa.Text(), nullable=True),
    sa.Column('overview_ru', sa.Text(), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('votes', sa.Integer(), nullable=True),
    sa.Column('popularity', sa.Float(), nullable=True),
    sa.Column('imdb_movie', sa.Integer(), nullable=False),
    sa.Column('movie_collection', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['imdb_movie'], ['imdb_movie.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movie_collection'], ['collection.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('imdb_movie'),
    sa.UniqueConstraint('tmdb_mvid')
    )
    op.create_table('movie_country',
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('imdb_movie_id', sa.Integer(), nullable=False),
    sa.Column('tmdb_movie_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['imdb_movie_id'], ['imdb_movie.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tmdb_movie_id'], ['tmdb_movie.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_id', 'imdb_movie_id'),
    sa.UniqueConstraint('country_id', 'tmdb_movie_id')
    )
    op.create_table('movie_production',
    sa.Column('production_company_id', sa.Integer(), nullable=False),
    sa.Column('imdb_movie_id', sa.Integer(), nullable=False),
    sa.Column('tmdb_movie_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['imdb_movie_id'], ['imdb_movie.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['production_company_id'], ['production_company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tmdb_movie_id'], ['tmdb_movie.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('production_company_id', 'imdb_movie_id'),
    sa.UniqueConstraint('production_company_id', 'tmdb_movie_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie_production')
    op.drop_table('movie_country')
    op.drop_table('tmdb_movie')
    op.drop_table('movie_principal')
    op.drop_table('movie_genre')
    op.drop_table('tmdb_person')
    op.drop_table('production_company')
    op.drop_table('person_profession')
    op.drop_table('imdb_movie')
    op.drop_table('profession')
    op.drop_table('imdb_person')
    op.drop_table('genre')
    op.drop_table('country')
    op.drop_table('content_type')
    op.drop_table('collection')
    op.drop_table('__test_relation')
    # ### end Alembic commands ###
