"""empty message

Revision ID: 5a6bde24cd35
Revises: 7b30cd7ec90e
Create Date: 2024-05-04 17:51:38.247386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a6bde24cd35'
down_revision: Union[str, None] = '7b30cd7ec90e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('country', sa.Column('iso', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'country', ['iso'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'country', type_='unique')
    op.drop_column('country', 'iso')
    # ### end Alembic commands ###
