"""empty message

Revision ID: 68dd1ee99f71
Revises: e0ac8dc5cd92
Create Date: 2024-06-16 00:10:20.394797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68dd1ee99f71'
down_revision: Union[str, None] = 'e0ac8dc5cd92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('tmdb_id', sa.Integer(), nullable=False))
    op.add_column('production_company', sa.Column('tmdb_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('production_company', 'tmdb_id')
    op.drop_column('collection', 'tmdb_id')
    # ### end Alembic commands ###
