"""empty message

Revision ID: a3a37a750846
Revises: 3def51766410
Create Date: 2024-07-05 18:00:19.728392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3a37a750846'
down_revision: Union[str, None] = '3def51766410'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('person_profession_profession_fkey', 'person_profession', type_='foreignkey')
    op.drop_constraint('person_profession_person_fkey', 'person_profession', type_='foreignkey')
    op.drop_column('person_profession', 'profession')
    op.drop_column('person_profession', 'person')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person_profession', sa.Column('person', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('person_profession', sa.Column('profession', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('person_profession_person_fkey', 'person_profession', 'imdb_person', ['person'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('person_profession_profession_fkey', 'person_profession', 'profession', ['profession'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
