"""empty message

Revision ID: b375eec8fb22
Revises: 8094ad31c213
Create Date: 2024-07-05 18:10:20.318906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b375eec8fb22'
down_revision: Union[str, None] = '8094ad31c213'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person_profession', sa.Column('profession_id', sa.Integer(), nullable=False))
    op.add_column('person_profession', sa.Column('person_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'person_profession', 'profession', ['profession_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'person_profession', 'imdb_person', ['person_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'person_profession', type_='foreignkey')
    op.drop_constraint(None, 'person_profession', type_='foreignkey')
    op.drop_column('person_profession', 'person_id')
    op.drop_column('person_profession', 'profession_id')
    # ### end Alembic commands ###
