"""empty message

Revision ID: bbeeaef001b2
Revises: 3c6a37ce9fbd
Create Date: 2024-05-08 09:42:46.325681

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bbeeaef001b2"
down_revision: Union[str, None] = "3c6a37ce9fbd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "imdb_person",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("imdb_nmid", sa.String(), nullable=False),
        sa.Column("name_en", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("birth_y", sa.Integer(), nullable=True),
        sa.Column("death_y", sa.Integer(), nullable=True),
        sa.Column("image_url", sa.String(), nullable=True),
        sa.Column("tmdb_added", sa.Boolean(), nullable=False),
        sa.Column("imdb_extra_added", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("imdb_nmid"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "profession",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("imdb_name", sa.String(), nullable=False),
        sa.Column("name_en", sa.String(), nullable=False),
        sa.Column("name_ru", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("imdb_name"),
    )
    op.create_table(
        "person_profession",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("profession", sa.Integer(), nullable=False),
        sa.Column("person", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["person"], ["imdb_person.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["profession"], ["profession.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tmdb_person",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("imdb_person", sa.Integer(), nullable=False),
        sa.Column("tmdb_nmid", sa.Integer(), nullable=False),
        sa.Column("name_en", sa.String(), nullable=False),
        sa.Column("name_ru", sa.String(), nullable=True),
        sa.Column("gender", sa.Integer(), nullable=False),
        sa.Column("image_url", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["imdb_person"], ["imdb_person.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("imdb_person"),
        sa.UniqueConstraint("tmdb_nmid"),
    )
    op.create_table(
        "movie_principal",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("imdb_movie", sa.Integer(), nullable=False),
        sa.Column("imdb_person", sa.Integer(), nullable=False),
        sa.Column("category", sa.Integer(), nullable=True),
        sa.Column("job", sa.String(), nullable=False),
        sa.Column("charachters", sa.ARRAY(sa.String()), nullable=True),
        sa.ForeignKeyConstraint(["category"], ["profession.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["imdb_movie"], ["imdb_movie.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["imdb_person"], ["imdb_person.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("movie_principal")
    op.drop_table("tmdb_person")
    op.drop_table("person_profession")
    op.drop_table("profession")
    op.drop_table("imdb_person")
    # ### end Alembic commands ###
