"""empty message

Revision ID: cc5914fd168d
Revises: 2ec68ed960fb
Create Date: 2024-06-23 12:40:20.051983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc5914fd168d'
down_revision: Union[str, None] = '2ec68ed960fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('imdb_movie', sa.Column('start_year', sa.Integer(), nullable=False))
    op.add_column('imdb_movie', sa.Column('end_year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('imdb_movie', 'end_year')
    op.drop_column('imdb_movie', 'start_year')
    # ### end Alembic commands ###
