"""empty message

Revision ID: e0ac8dc5cd92
Revises: bbeeaef001b2
Create Date: 2024-05-09 19:59:22.494810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0ac8dc5cd92'
down_revision: Union[str, None] = 'bbeeaef001b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genre', sa.Column('name_en', sa.String(), nullable=False))
    op.alter_column('genre', 'name_ru',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('genre_imdb_name_key', 'genre', type_='unique')
    op.create_unique_constraint(None, 'genre', ['name_en'])
    op.drop_column('genre', 'imdb_name')
    op.add_column('imdb_movie', sa.Column('name_en', sa.String(), nullable=False))
    op.add_column('imdb_movie', sa.Column('name_ru', sa.String(), nullable=True))
    op.drop_column('imdb_movie', 'title_en')
    op.drop_column('imdb_movie', 'title_ru')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('imdb_movie', sa.Column('title_ru', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('imdb_movie', sa.Column('title_en', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('imdb_movie', 'name_ru')
    op.drop_column('imdb_movie', 'name_en')
    op.add_column('genre', sa.Column('imdb_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'genre', type_='unique')
    op.create_unique_constraint('genre_imdb_name_key', 'genre', ['imdb_name'])
    op.alter_column('genre', 'name_ru',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('genre', 'name_en')
    # ### end Alembic commands ###
